### PR TITLE
BSS considers rings to be broken also when they are not

### PR DESCRIPTION
**Pull request by ptosco**
The changes introduced to address #99 disallow adding a whole ring where there was none, which should be allowed.
Currently this transformation is disallowed:
```
                        CH2-CH2
0   1         0   1    /       \
CH3-CH3 ----> CH3-CH2-CH       CH2
                       \       /
                        CH2-CH2
```
as atom 1 is not adjacent to a ring in state 1 while it is in state 2, and as a consequence `_is_ring_broken()` returns `True`. However,  no ring is broken as a whole new ring is added in this case.
Also, the `_onRing function` would return false for atom 0 in this case:
```
      CH2-CH2     CH2-CH2
     /       \    /      \
CH3-CH     0 CH-CH       CH2
     \       /    \      /
      CH2-CH2     CH2-CH2
```
because as atom 0 is in a ring, in addition to be adjacent to a ring, so _onRing() would return immediately `False` due to this early `if` clause:
```
    # The atom is in a ring.
    if conn.inRing(idx):
        return False
```
So in such a case the whole ring addition transformation would be allowed because `_is_ring_broken()` would return `False`, which is inconsistent.
Removing the `onRing()` check altogether does not seem to break any unit test.
@lohedges Does the above make sense to you?

### CODE REVIEW

**Comment by lohedges** [comment]
This makes complete sense, but I get the following test failures here:

```
test/Align/test_align.py::test_prematch[prematch0] PASSED                                                                                              [  7%]
test/Align/test_align.py::test_prematch[prematch1] PASSED                                                                                              [ 14%]
test/Align/test_align.py::test_prematch[prematch2] PASSED                                                                                              [ 21%]
test/Align/test_align.py::test_prematch[prematch3] PASSED                                                                                              [ 28%]
test/Align/test_align.py::test_invalid_prematch[prematch0] PASSED                                                                                      [ 35%]
test/Align/test_align.py::test_invalid_prematch[prematch1] PASSED                                                                                      [ 42%]
test/Align/test_align.py::test_invalid_prematch[prematch2] PASSED                                                                                      [ 50%]
test/Align/test_align.py::test_invalid_prematch[prematch3] PASSED                                                                                      [ 57%]
test/Align/test_align.py::test_merge PASSED                                                                                                            [ 64%]
test/Align/test_align.py::test_ring_breaking_three_membered FAILED                                                                                     [ 71%]
test/Align/test_align.py::test_ring_breaking_five_membered PASSED                                                                                      [ 78%]
test/Align/test_align.py::test_ring_breaking_six_membered PASSED                                                                                       [ 85%]
test/Align/test_align.py::test_ring_size_change[ligands0] FAILED                                                                                       [ 92%]
test/Align/test_align.py::test_ring_size_change[ligands1] PASSED                                                                                       [100%]
```

The tests that failed were why the `onRing` logic was introduced. I'll have a think about this, since clearly I didn't consider the ring growth example that you show.

**Comment by ptosco** [comment]
Ah, OK, I thought I should have broken something! Let me have a 2nd look then.

**Comment by lohedges** [comment]
No problem. I think this is a difficult problem and there are clearly a lot of edge cases to address. I was basically using whatever information that I could extract from the Sire `Connectivity` object, but it might be required that we supplement the information somehow. I also think that the order in which checks are done (to eliminate various situations) will be quite important.

**Comment by lohedges** [comment]
Do you have some example input files for this so that I can debug locally and write some tests?

**Comment by ptosco** [comment]
[growring.tar.gz](http://1b3211c549dbdbb4dbb9-1f72b29fc48de44749ce23b81e3e52fc.r32.cf3.rackcdn.com/growring.tar.gz)

**Comment by lohedges** [comment]
Great. I'll take a look this afternoon.

**Comment by ptosco** [comment]
@lohedges This seems to get all tests to pass (including the new one).

**Comment by lohedges** [comment]
Many thanks for this, and for the unit test too. I'll check it against the other problem mappings from a few of the other issue threads and merge when I'm happy.

**Comment by lohedges** [comment]
The changes don't cause any issues with any of the other problem mappings that had previously been fixed. There are still issues with the recent mappings mentioned in [this](https://github.com/michellab/BioSimSpace/issues/99) thread, but I think those are the result of different bugs and can be debugged independently.

I'm happy that we're moving in the right direction. Thanks again for catching this, and for the elegant fix.

**Comment by ptosco** [comment]
Thanks a lot!

**Comment by lohedges** [comment]
Just to say that the ligand pair at the bottom of [this](https://github.com/michellab/BioSimSpace/issues/99) issue (the `p38` pair) appears to have been missed by the ring-breaking/growing checks. I'm working on catching this perturbation but let me know if you have any suggestions.

**Pull request merged**
