### PR TITLE
[WIP] Allow the Free Energy Protocol to write multiple lambda states from the Free Energy Protocol

### PR DESCRIPTION
**Pull request by xiki-tempula**
Working in progress now.
Enable the Free Energy Protocol to write multiple lambda states.

### CODE REVIEW

**Comment by lohedges** [comment]
Just to note that CI isn't currently setup to run against external forks, hence the failures. I you want to test your code, then you'll need to run the tests locally.

**Comment by xiki-tempula** [comment]
@lohedges Thanks.

**Comment by lohedges** [comment]
Also, is there a reason is a PR against _our_ devel branch, rather than the EXS one? The development strategy should be that you PR against your own devel. When that is merged then you can do a PR against our devel. (Otherwise the sandpit approach is pointless and we're not simplifying the development / maintenance burded.)

**Comment by lohedges** [comment]
I'll close this now. Please move your PR to https://github.com/Exscientia/BioSimSpace/pulls, since internal features should be PR'ed against your _own_ development branch. In any case, I am not a fan of WIP PR's since they trigger _many_ redundant CI builds and email notifications.

As mentioned last week, please give informative commit messages where possible. I know that these can be squashed, but it loses the paper-trail for debugging purposes.

**Comment by xiki-tempula** [comment]
@lohedges Sorry, I thought that I point it towards the Exscientia/devel since I open the PR in the Exscientia repo but apparently the it still defaults to the michellab/devel.

**Comment by lohedges** [comment]
Ah, I think GitHub changed things at some point so that PRs always point to the original repo, even on forks. I think there is a drop-down where you can select the correct fork for the base.

Cheers.

**Comment by xiki-tempula** [comment]
@lohedges I have changed it now. Thanks.

**Pull request closed without merging**
